apiVersion: config.istio.io/v1alpha2
kind: DestinationPolicy
metadata:
  name: httpbin-cb
  namespace: default
spec:
  destination:
    name: httpbin
    labels:
      version: v1
  circuitBreaker:
    simpleCb:
      maxConnections: 1
      httpMaxRequests: 1
      httpMaxPendingRequests: 1
      httpMaxRequestsPerConnection: 2
      sleepWindow: 15m
      httpDetectionInterval: 1ms
      #httpConsecutiveErrors: 1
      #httpMaxEjectionPercent: 100
  loadBalancing:
    name: ROUND_ROBIN
