apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  name: httpbin-503
  namespace: default
spec:
  destination:
    name: httpbin
  match:
    request:
      headers:
        uri:
          prefix: /httpbin/status/503
  rewrite:
    uri: /status/503
  route:
  - labels:
      version: v1
  precedence: 1
